version: '3.3'

services:
  kokoro-tts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api
    ports:
      - "8880:8880"
    environment:
      - PYTHONPATH=/app:/app/api
      - ONNX_NUM_THREADS=8
      - ONNX_INTER_OP_THREADS=4
      - ONNX_EXECUTION_MODE=parallel
      - ONNX_OPTIMIZATION_LEVEL=all
      - ONNX_MEMORY_PATTERN=true
      - ONNX_ARENA_EXTEND_STRATEGY=kNextPowerOfTwo
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

  # gradio-ui:
  #   image: ghcr.io/remsky/kokoro-fastapi-ui:v${VERSION}
  #   ports:
  #     - "7860:7860"
  #   depends_on:
  #     - kokoro-tts
